### ISSUE TITLE
Contents and repositories for JuliaMath

### ISSUE THREAD

**Issue by ararslan** [JuliaMath/Roadmap.jl#1]
Let's figure out what we want to adopt from other organizations and what new things we should have.
- Number theory
  - [x] Primes (from Base--see JuliaLang/julia#16357)
  - [ ] Elliptic curves
  - [ ] ~~Continued fractions ([johnmyleswhite/ContinuedFractions.jl](https://github.com/johnmyleswhite/ContinuedFractions.jl))?~~
- Special functions
  - [x] Special functions ([nolta/SpecialFunctions.jl](https://github.com/nolta/SpecialFunctions.jl))
- Combinatorics
  - [x] Combinatorics ([JuliaLang/Combinatorics.jl](https://github.com/JuliaLang/Combinatorics.jl))
- Calculus
  - [x] Root finding ([JuliaLang/Roots.jl](https://github.com/JuliaLang/Roots.jl))
  - [ ] ~~Differential equations ([JuliaLang/ODE.jl](https://github.com/JuliaLang/ODE.jl))~~
  - [ ] ~~Differentiation/integration ([johnmyleswhite/Calculus.jl](https://github.com/johnmyleswhite/Calculus.jl))?~~
- Topology
  - [ ] Homology, complexes, ...
- Linear algebra
  - [ ] LinAlg? (if those functions get removed from Base)
  - [x] Iterative solvers ([JuliaLang/IterativeSolvers.jl](https://github.com/JuliaLang/IterativeSolvers.jl))
- Arithmetic/numerics
  - [ ] Double-double arithmetic ([simonbyrne/DoubleDouble.jl](https://github.com/simonbyrne/DoubleDouble.jl))
- Bindings for libraries
  - [x] Yeppp! ([JuliaLang/Yeppp.jl](https://github.com/JuliaLang/Yeppp.jl))
  - [ ] ~~Sundials ([JuliaLang/Sundials.jl](https://github.com/JuliaLang/Sundials.jl))~~
  - [x] VML
  - [x] Apple Accelerate

What do you think of these? What else?

**Comment by ararslan** [comment]
@jiahao @andreasnoack -- Perhaps relevant to your interests as well?

**Comment by mschauer** [comment]
Should there be a MathCore.jl library providing basic functionality to break up interdependencies?

**Comment by p-zubieta** [comment]
Also, I don't know if there is interest on the part of @jverzani or @wbhart to migrate their CAS (SymPy.jl and Nemo.jl), for example, to an organization.

**Comment by wbhart** [comment]
We already have moved Nemo.jl to an organisation on GitHub. We just don't
have a release from the org yet. But one is coming soon enough.

https://github.com/Nemocas/Nemo.jl

Bill.

**Comment by jverzani** [comment]
There are no reasons SymPy couldn't move over save intertia.

**Comment by ararslan** [comment]
@mschauer What kind of interdependencies do you imagine would occur and what would you propose to go in a core math repo?

**Comment by mschauer** [comment]
In the moment of writing I thought about a module Primes including a module SpecialFunctions to call the logarithmic integral function and a reverse dependency for example via quasi montecarlo integration methods but there are likely better examples.

**Comment by ChrisRackauckas** [comment]
What about number libraries like doubledouble? And what about PetsC?

**Comment by ararslan** [comment]
@ChrisRackauckas I don't know what those are. Can you gimmeh teh linkz pls?

**Comment by ChrisRackauckas** [comment]
[PetsC.jl](https://github.com/JuliaParallel/PETSc.jl) is a popular package for sparse solvers and other tools for computational PDEs.

[Doubledouble.jl](https://github.com/simonbyrne/DoubleDouble.jl) implements quad precision arithmetic.

I'd be interested in migrating my package [DifferentialEquations.jl](https://github.com/ChrisRackauckas/DifferentialEquations.jl) which is for "non-ordinary" differential equations (adding my stochastic differential equations parts next weekend?)

**Comment by ararslan** [comment]
Hm, JuliaParallel already owns PETSc and since it depends on MPI it probably makes more sense for them to keep it.

Your DifferentialEquations.jl would probably fit here, though the name is a little misleading as it doesn't include ODEs. Org members: What do you think?

@simonbyrne What would you think about migrating your DoubleDouble.jl to JuliaMath? Do you think this would be an appropriate home for it?

**Comment by simonbyrne** [comment]
Yes, I would be happy to move DoubleDouble.jl.

**Comment by ChrisRackauckas** [comment]
I think [NLSolve.jl](https://github.com/EconForge/NLsolve.jl) would be a good fit here, but it's also in an org. 

For symbolic math another interesting development is [Sjulia](https://github.com/jlapeyre/SJulia.jl).

**Comment by ararslan** [comment]
@simonbyrne Awesome! Feel free to transfer at your leisure. :smile:

**Comment by ararslan** [comment]
@ChrisRackauckas NLSolve probably belongs in JuliaOpt more than anywhere else, I would think. As for SJulia, I think we should keep an eye on it as it matures.

**Comment by ararslan** [comment]
I saw an old julia-dev post where @StefanKarpinski mentioned that an organization like this would be quite broad. I definitely agree with that. As such I think we should think carefully about the scope of the organization and what does and does not belong here. I'd especially be interested in input from others on what does _not_ belong here.

**Comment by ChrisRackauckas** [comment]
I think to complete my list, [Brownian.jl](https://github.com/UniversityofWarwick/Brownian.jl) would be a good fit.

But what about linking libraries? Things like MATLAB.jl and Mathematica.jl?

**Comment by ararslan** [comment]
Would stochastic processes not fall under the umbrella of JuliaStats? I'm not really sure how they've defined their scope.

**Comment by ararslan** [comment]
Regarding Matlab and Mathematica, I wouldn't consider those on topic here. (Even my proposal of Yeppp! and Sundial is kind of pushing it, I think.) Matlab and Mathematica would be a better fit for [the proposed JuliaInterop org](https://groups.google.com/forum/#!topic/julia-dev/gykIyx0Jjwo), if that comes to fruition. Edit: Looks like it probably won't. But I'd still consider those packages outside of our scope.

**Comment by ChrisRackauckas** [comment]
I agree with the Interop. As for stochastic processes, I think that would go with math instead of stats. Stats uses stochastic processes and many statistical tests/algorithms build on ideas from stochastic processes, but the core of stochastic processes is still over to math. I think that's why you'd find people researching stochastic processes more centered in mathematics departments (though they have a large spread through other fields as well).

I think we need to define a bit about what is JuliaMath. I would be under the impression that it deals with at least everything from "traditional applied math", such as computational PDEs, numerical linear algebra,  dynamical systems, and numerical analysis. These days the departments tend to include stochastic differential equations and computational algebra.

Maybe there are two different orgs that should be made: one based on numerics (numerical analysis and numerical linear algebra), and one based on dynamics (ODEs, PDEs, SDEs, control systems, bifurcation analysis, etc.). But if the key idea is to pull them together for cross-contributions, numerical linear algebra should really be kept with PDEs since they are really closely related in practice.

**Comment by ararslan** [comment]
I agree with your definition for org, though I think numerics and dynamics can coexist here just fine.

With the "computational" aspect in mind, I think that symbolic manipulations and other CAS stuff should not live here. That would include things like SymPy, Nemo, and SJulia (arguably Calculus.jl as well). Hopefully that wouldn't be too controversial for @pabloferz, who specifically mentioned CAS. 😄

**Comment by simonbyrne** [comment]
Honestly, I would be careful about moving too many repos too early, otherwise orgs have a danger of ending up full of abandonware. I would start with a few (or create the new ones), and go from there.

**Comment by p-zubieta** [comment]
Following @simonbyrne, I think, for the time being, we should focus in accommodate here those parts from Base that fit here.

**Comment by simonbyrne** [comment]
I would nominate Primes.jl and SpecialFunctions.jl as good places to start.

**Comment by musm** [comment]
Same with Simon, I feel like this should start of as a small set of curated packages that are essential and of high quality  (a la  matlab toolboxes) and the maybe go from there.

**Comment by mschauer** [comment]
> then maybe go from there.

Let's not overshoot in the other direction though.

**Comment by simonbyrne** [comment]
We could also start by moving the relevant ones from the JuliaLang org as well.

**Comment by ararslan** [comment]
Yes, all of that sounds great to me. When I was naming packages before, I was thinking more long term; I absolutely agree that we should start small.

Perhaps once @mschauer's and @pabloferz's outstanding PRs for primes.jl (JuliaLang/julia#16333 and JuliaLang/julia#16349, respectively) are merged, we can branch out a Primes repo.

**Comment by simonbyrne** [comment]
[Primes.jl](https://github.com/JuliaMath/Primes.jl) has now been created!

**Comment by ararslan** [comment]
@simonbyrne Awesome, thanks! How will that work with Pablo and M.'s PRs on base Julia?

**Comment by p-zubieta** [comment]
I guess we can close them over there and bring them here.

**Comment by simonbyrne** [comment]
I've changed the permissions so that all members have commit access, so @pabloferz and @mschauer you should feel free to move your PRs over (and make any other changes you feel deserving).

**Comment by tkelman** [comment]
Why is Sundials.jl crossed out? I'm about to raise an issue there, either JuliaMath or JuliaODE (which currently only has a fork of ODE.jl) would be good places for that to move to.

**Comment by ChrisRackauckas** [comment]
It's crossed out because it was being put as an "Interop package". ODEInterface would be in the same boat.

**Comment by tkelman** [comment]
Well ODEInterface isn't in JuliaLang so it doesn't necessarily need to move except for the sake of making it easier for multiple people to help with maintenance.

**Comment by ChrisRackauckas** [comment]
Oh, I didn't know Sundials was in JuliaLang.

**Comment by ararslan** [comment]
@tkelman What do you mean it's crossed out... >_>

**Comment by ChrisRackauckas** [comment]
ODE.jl should be crossed out because of the new JuliaDiffEq org.

**Comment by ararslan** [comment]
~~If there's an organization specifically for differential equations, wouldn't it make more sense for them to have Sundials?~~

Looks like it was already moved.

**Comment by ChrisRackauckas** [comment]
@simonbyrne what has happened with the GSoC projects by @sunoru? It seems like [VSL.jl](https://github.com/sunoru/VSL.jl) and [RNG.jl](https://github.com/sunoru/RNG.jl) are very good starts, but seem to be abandoned since GSoC ended (1 month of no commits). Would these be good candidates to move here so we could continue to develop them? (RNG.jl in particular looks like a very promising result)

**Comment by sunoru** [comment]
Hi Chris. I'm so sorry that I have been kind of busy in this new semester, but I haven't abandoned the project. There are many TODOs in RNG.jl.

**Comment by ararslan** [comment]
@sunoru You're doing great work on that project. I hope you enjoyed GSoC and I'm glad you're still interested in maintaining those packages. Keep up the good work! 👍

**Comment by ChrisRackauckas** [comment]
Good to hear. I put in some PRs to fix the testing and requirements. I noticed these were odd (not including v0.5, and while requiring only v0.5-) which is why I was wondering if it was still under development.

**Comment by sunoru** [comment]
@ararslan Thank you very much! I'll keep doing my best.

There are some existing issues and todos. You are welcomed to join the discussion if you are interested.

**Comment by ChrisRackauckas** [comment]
Closing this since the broad changes have already occurred. Other migrations should be new issues.
