### ISSUE TITLE
JuliaMath organization details

### ISSUE THREAD

**Issue by ararslan** [JuliaMath/Roadmap.jl#2]
It appears JuliaStats has a website, a Google group, an org description, an expanded name ("Julia Statistics"), and a logo (which will hopefully be unique soon). I think we should definitely do the latter three and perhaps the former two once we've grown more.

Here's what I'm thinking:
Description: Mathematics made easy in Julia
Expanded name: Julia Mathematics
Logo: _Definitely_ @mschauer's proposal using Julia sets

(Admittedly that proposed description is stolen from JuliaStats). What say ye?

---

Stuff to do:
- [x] Expanded organization name
- [x] Organization description
- [x] Logo
- [x] Google Group
- [ ] Website
- [x] Gitter

**Comment by tkelman** [comment]
I made you an owner here, since you're encouragingly enthusiastic about it. Everything you propose sounds great, as does your list of packages in #1.

**Comment by ararslan** [comment]
@tkelman Thanks! 🎉

**Comment by ChrisRackauckas** [comment]
JuliaMath should definitely get a Gitter. The Gitter communities are pretty key to Julia.

**Comment by ararslan** [comment]
@ChrisRackauckas That's a good idea. I'll put that on the to-do list.

**Comment by ChrisRackauckas** [comment]
I'd be interested in helping JuliaMath get this together.

**Comment by simonbyrne** [comment]
@ChrisRackauckas I've invited you to join the org. I don't know anything about gitter, but if you need more permissions let me know.

**Comment by ChrisRackauckas** [comment]
Someone with owner permissions needs to accept the OAuth I requested (it should email you?). I'll use that to set the org channel to public so it's not tied to a repo (I think owner permissions are needed for this since the org isn't showing up)

**Comment by ChrisRackauckas** [comment]
It looks like I'll need more permissions. Also, is anyone looking into putting together the site?

**Comment by ararslan** [comment]
I don't know that we'd have much to say on a site at the moment. Maybe once the primes deprecation makes its way into the Julia news.

**Comment by ChrisRackauckas** [comment]
I'll probably get one up and running a few weeks from now then. I think it should get put together so that future changes are easy: just update the text.

**Comment by ararslan** [comment]
Gitter: https://gitter.im/JuliaMath/Roadmap.jl

**Comment by ChrisRackauckas** [comment]
I noticed on the Google Group it says "Here we discuss mathematical programming in Julia". Mathematical programming is definitely not what we cover: that would be in JuliaOpt.

**Comment by ararslan** [comment]
I've heard linear and nonlinear programming used to refer to optimization but not mathematical programming. I'd be happy to change it if you have a better suggestion though.

**Comment by ChrisRackauckas** [comment]
It's pretty common, https://en.wikipedia.org/wiki/Mathematical_optimization 

Maybe something like "Here we discuss using Julia to solve mathematical problems"?

**Comment by tkelman** [comment]
e.g. http://www.ismp2015.org/ (we had a whole Julia session there last year, was a little JuliaOpt party)

**Comment by ararslan** [comment]
@ChrisRackauckas Nice, changed to that.
