### ISSUE TITLE
Simple new logo

### ISSUE THREAD

**Issue by musm** [JuliaMath/Roadmap.jl#4]
I propose the following replacement  (Inspired by Waldir Pimenta   https://groups.google.com/forum/#!topic/julia-users/rahjsS_OW4g cc: @waldyrious)
![julia-math](https://cloud.githubusercontent.com/assets/4319522/19166231/c4480da2-8bd4-11e6-9970-6a8fe88d0db1.jpg)

**Comment by ararslan** [comment]
I actually prefer @mschauer's Julia set logo, which we're currently using, which was [very well received](https://github.com/JuliaLang/julia/issues/16357#issuecomment-219693645).

**Comment by musm** [comment]
This logo is also harmonious with the JuMP logo: http://www.juliaopt.org/images/juliaopt.svg

And the new  Julia-i18n logo:  http://imgh.us/julia-i18n-j.svg

It's better that all Julia logos for the major orgs follow the same design principles for clarity and harmony and unity.

**Comment by ararslan** [comment]
I disagree--I don't think having matching logos across unrelated organizations is a necessity. Several organizations have logos that entirely deviate from the three dots theme, with particularly notable examples being [BioJulia](https://github.com/BioJulia) and [JuliaArrays](https://github.com/JuliaArrays).

**Comment by waldyrious** [comment]
@musm I'm stoked that you liked the julia-i18n logo so much :) I would have made this variation myself (didn't have time to properly answer to the julia-users thread), but as I had said previously, and @ararslan reinforced here, the julia-set logo was actually very well received when it was first proposed.

However, this logo would be great for a [MathConstants](https://en.wikipedia.org/wiki/Mathematical_constant) package, similar to [PhysicalConstants.jl](https://github.com/DataWookie/PhysicalConstants.jl), if one is ever created :)
