### ISSUE TITLE
Migration of RNG.jl

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaMath/Roadmap.jl#5]
I think RNG.jl should be migrated to JuliaMath so that way it can start becoming a more standard part of Julia, maintained by more members of the community. 

@sunoru 
@ViralBShah

**Comment by ararslan** [comment]
I would argue that packages under organizations are no more a "standard part of Julia" than packages under personal accounts. A notable example is Gadfly, which lived under Daniel's personal account from its inception until about a month ago. I think that it only really makes sense to move a repository from a personal account to an organization if the original owner is no longer actively developing it (as was the case with Gadfly) and the organization members are interested in picking it up. Repos on personal accounts can still have collaborators, receive issues and pull requests, etc.

So in all, this seems unnecessary to me unless Sunoru is no longer interested in developing or maintaining RNG.jl.

**Comment by ViralBShah** [comment]
I suggest doing so, if there is at least one person in JuliaMath interested in ownership/maintenance. It certainly would be the right place to belong, but @sunoru should decide what is best.
