### ISSUE TITLE
Home for FixedPointDecimals.jl

### ISSUE THREAD

**Issue by omus** [JuliaMath/Roadmap.jl#6]
As per the [discussion in Currencies.jl](https://github.com/JuliaFinance/Currencies.jl/pull/77#issuecomment-301228998) the FixedPointDecimals module should be separated from [Currencies.jl](https://github.com/JuliaFinance/Currencies.jl) and made into its own package. Under the recommendation of @TotalVerb I created the package [FixedPointDecimals.jl](https://github.com/JuliaMath/FixedPointDecimals.jl) under the JuliaMath organization. 

The package itself allows decimal numbers to be stored exactly and avoids issues with floating-point arithmetic. 

Do members of JuliaMath feel that this package should be registered in the JuliaMath org or somewhere else like JuliaFinance?

**Comment by ararslan** [comment]
JuliaMath wouldn't have been the first place I would have suggested for it, but I don't think it's completely out of place or anything like that. JuliaFinance may be an okay place for it as well.

**Comment by TotalVerb** [comment]
I do like JuliaMath for this, because it has more maintainers and thus a higher [bus factor](https://en.wikipedia.org/wiki/Bus_factor).

**Comment by ararslan** [comment]
> it has more maintainers

For some things, sure. I personally don't intend to do much maintenance of FixedPointDecimals unless it becomes strictly necessary, just as other members don't touch various other packages much.

**Comment by omus** [comment]
I'll leave the package in JuliaMath as there are no strong objections.
